awesome_answers1/awesome_answers/config/routes.rb
AwesomeAnswers::Application.routes.draw do

get "/about_us" => "home#about"
get "/faq" => "home#faq"
get "/help" => "help#index"

resources :questions, except:[:index] do
member do
  post :vote_up
  post :vote_down
end
post :search, on: :collection
end

root "questions#index"

end

awesome_answers1/awesome_answers/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

awesome_answers1/awesome_answers/app/controllers/help_controller.rb
class HelpController < ApplicationController

def index
end

end

awesome_answers1/awesome_answers/app/controllers/home_controller.rb
class HomeController < ApplicationController

  def about
  end

  def faq
  end
  
end

awesome_answers1/awesome_answers/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
  end

  def create
  end

  def show
  render text: "The ID is: #{params[:id]}"
  end

  def edit
  end

  def vote_up
  end

  def vote_down
  end

  def destroy
     render text: "deleting!!"
  end

  def search
  end


end

awesome_answers1/awesome_answers/app/helpers/application_helper.rb
module ApplicationHelper
end

awesome_answers1/awesome_answers/app/helpers/help_helper.rb
module HelpHelper
end

awesome_answers1/awesome_answers/app/helpers/home_helper.rb
module HomeHelper
end

awesome_answers1/awesome_answers/app/helpers/questions_helper.rb
module QuestionsHelper
end

awesome_answers1/awesome_answers/app/views/help/index.html.erb
<%= link_to "About Us", about_us_path %>
<br>

<%= link_to "Edit Questions", edit_question_path[1] %> 
<%= link_to "Delete Questions", question_path[1], method: :delete %> 
<br>

<h1>Welcome to my help page</h1>

awesome_answers1/awesome_answers/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AwesomeAnswers</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>